import Nav from "@/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav />
      {children}
    </>
  );
}
