import Nav from "@/components/Nav";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Playfair_Display } from "next/font/google";
import ClientMessageDisplay from "./ClientMessageDisplay";

const font = Playfair_Display({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-alabaster ${font.className}`}>
        <ClientMessageDisplay />
        <Nav />
        {children}
      </body>
    </html>
  );
}
